### ISSUE TITLE
Sorry. Off-topic... ONEWHEEL

### ISSUE THREAD

**Issue by vfear** [Knifa/tower-tool#30]
I didn't know how to contact you. I'm very interested in your work on https://github.com/Knifa/hoverboard-firmware-hack-FOC Does it work? I tried to run the firmware, but the motors don't work. Please help me, please. I'm making my ONEWHEEL.
mail: vfear_777@mail.ru

**Comment by Knifa** [comment]
It worked a bit but it was not nearly as smooth as a real Onewheel. Too much going on in the original repo and not enough knowledge about how motors work. :smile: The people who were interested in our group got real Onewheels and I stopped looking into it. Just getting a real unit or looking at VESCs seemed like a better option. 👍

**Comment by verial** [comment]
I am also very interested in this topic to continue it does not work out?

**Comment by Knifa** [comment]
No, it didn't work very well even after tuning PIDs. :(

**Comment by vfear** [comment]
I flashed the board. My wheels don't turn. What could it be?

**Comment by verial** [comment]
0.019988416666667,Async Serial,'171'
0.019999333333333,Async Serial,'0'
0.020010250000000,Async Serial,'0'
0.020021166666667,Async Serial,'0'
0.020032083333333,Async Serial,'0'
0.020043000000000,Async Serial,'0'
0.020053916666667,Async Serial,'0'
0.020064833333333,Async Serial,'0'
0.020075750000000,Async Serial,'0'
0.020086750000000,Async Serial,'0'
0.020097666666667,Async Serial,'0'
0.020108583333333,Async Serial,'0'
0.020119500000000,Async Serial,'0'
0.020130416666667,Async Serial,'0'
0.020141333333333,Async Serial,'0'
0.020152250000000,Async Serial,'205'
0.020163166666667,Async Serial,'171'
0.029966666666667,Async Serial,'205'

there is an empty protocol.

**Comment by verial** [comment]
the LED I connected is responsive.

**Comment by Knifa** [comment]
I don't have the board to help you out with this anymore, unfortunately.

Make sure you flash the sideboard firmware as well if you haven't found that. There are changes in there.

https://github.com/Knifa/hoverboard-sideboard-hack-STM

**Comment by verial** [comment]
please tell me where you form the protocol?

**Comment by verial** [comment]
![image](https://user-images.githubusercontent.com/22721656/112712740-e242ad00-8ed9-11eb-85f5-989d72e78fcf.png)
